export const INTERVIEW_DOMAINS = {
  Technical: [
    'Frontend Development',
    'Backend Development',
    'Full Stack Development',
    'Mobile App Development',
    'Data Structures & Algorithms',
    'System Design',
    'Database Management',
    'Cloud Computing',
    'DevOps & SRE',
    'Cybersecurity',
    'QA & Testing',
    'Data Science',
    'Machine Learning & AI',
    'Networking',
    'Product & UI Engineering',
    'Embedded Systems & IoT',
    'Blockchain & Web3',
  ],
  HR: [
    'HR / Behavioral',
    'Communication',
    'Leadership & Teamwork',
    'Conflict Resolution',
    'Adaptability & Resilience',
    'Career Motivation',
    'Problem Solving',
    'Situational Judgment',
    'Work Ethic & Ownership',
    'Time Management & Prioritization',
    'Culture & Values',
    'People Management',
  ],
}
